name = "ADELIERegistry"
uuid = "852b4fb6-8a6a-4cb3-a31b-8236ad3d2adf"
repo = "https://github.com/ADELIE-Org/ADELIERegistry.git"

[packages]
178ba3f9-9d2c-41c2-b55a-b821a5514fe7 = { name = "CartesianGeometry", path = "C/CartesianGeometry" }
1ed6f371-fc45-4d53-9607-dafcbbd38b34 = { name = "AlgebraCore", path = "A/AlgebraCore" }
37466282-f9df-4509-9b24-142db341d2b3 = { name = "FieldAlgebra", path = "F/FieldAlgebra" }
5a5c722d-174f-4204-bea3-ae8e35ab7e08 = { name = "CartesianGrids", path = "C/CartesianGrids" }
5dfd4713-e1de-4e17-8e01-e86ec405dc37 = { name = "ISOAP", path = "I/ISOAP" }
60794e7d-98f0-4a77-a4fa-730d5cb83166 = { name = "ScalarAlgebra", path = "S/ScalarAlgebra" }
748854df-1f9f-4779-a286-58a21c3af615 = { name = "VOFTools", path = "V/VOFTools" }
7d1c641b-05d2-41e0-abea-6495ab56cdc9 = { name = "FrontSpaceTimeDEC", path = "F/FrontSpaceTimeDEC" }
9ebbbdc3-ccde-421a-bbc9-ca81de7cf635 = { name = "VofiJul", path = "V/VofiJul" }
a2ef5bc0-ae0c-4286-934f-9b0375ad7002 = { name = "Vofinit", path = "V/Vofinit" }
b6d9925f-6097-43d4-b8ff-c6cf6db146cf = { name = "FrontIntrinsicOps", path = "F/FrontIntrinsicOps" }
c559c034-0266-41c8-b9de-12815527c88c = { name = "FrontCartesianGeometry", path = "F/FrontCartesianGeometry" }
