name = "ADELIERegistry"
uuid = "852b4fb6-8a6a-4cb3-a31b-8236ad3d2adf"
repo = "https://github.com/ADELIE-Org/ADELIERegistry.git"

[packages]
178ba3f9-9d2c-41c2-b55a-b821a5514fe7 = { name = "CartesianGeometry", path = "C/CartesianGeometry" }
1ed6f371-fc45-4d53-9607-dafcbbd38b34 = { name = "AlgebraCore", path = "A/AlgebraCore" }
37466282-f9df-4509-9b24-142db341d2b3 = { name = "FieldAlgebra", path = "F/FieldAlgebra" }
5226656d-333b-451f-9f35-c95670ce899b = { name = "AdelieFlow", path = "A/AdelieFlow" }
5a5c722d-174f-4204-bea3-ae8e35ab7e08 = { name = "CartesianGrids", path = "C/CartesianGrids" }
5dfd4713-e1de-4e17-8e01-e86ec405dc37 = { name = "ISOAP", path = "I/ISOAP" }
60794e7d-98f0-4a77-a4fa-730d5cb83166 = { name = "ScalarAlgebra", path = "S/ScalarAlgebra" }
748854df-1f9f-4779-a286-58a21c3af615 = { name = "VOFTools", path = "V/VOFTools" }
750d4d02-2cfc-4aad-be47-7ed1619ca250 = { name = "AdelieValidation", path = "A/AdelieValidation" }
7d1c641b-05d2-41e0-abea-6495ab56cdc9 = { name = "FrontSpaceTimeDEC", path = "F/FrontSpaceTimeDEC" }
86518211-ffdd-4af2-8f3c-85d418569ed1 = { name = "AdelieOperators", path = "A/AdelieOperators" }
9025cefa-3883-48b0-bd9b-a8ff01ddb5b9 = { name = "CutCellConditions", path = "C/CutCellConditions" }
9ebbbdc3-ccde-421a-bbc9-ca81de7cf635 = { name = "VofiJul", path = "V/VofiJul" }
a2ef5bc0-ae0c-4286-934f-9b0375ad7002 = { name = "Vofinit", path = "V/Vofinit" }
ab87955b-22ac-4afb-a41c-38f9f0782a75 = { name = "AdelieScalar", path = "A/AdelieScalar" }
b6d9925f-6097-43d4-b8ff-c6cf6db146cf = { name = "FrontIntrinsicOps", path = "F/FrontIntrinsicOps" }
c43cbfc4-029e-427d-992e-0bd3014d182c = { name = "AdelieDarcy", path = "A/AdelieDarcy" }
c559c034-0266-41c8-b9de-12815527c88c = { name = "FrontCartesianGeometry", path = "F/FrontCartesianGeometry" }
d53fac3a-480b-4ec7-b354-fa680b5ce5e6 = { name = "InterfaceMotion", path = "I/InterfaceMotion" }
f40adccb-759d-4300-94a0-e63f3074ef8f = { name = "AdeliePhaseChange", path = "A/AdeliePhaseChange" }
fd383b27-61ae-43b9-be84-d33fac72113e = { name = "AdelieSolverCore", path = "A/AdelieSolverCore" }
